name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.10.6'
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.3
  flutter_icons:
    git:
      url: https://github.com/jibiel/flutter-icons.git
  font_awesome_flutter: ^10.6.0

  #*Architecture
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  responsive_builder: ^0.7.0
  get_it: ^7.2.0
  injectable: ^2.3.2
  flutter_hooks: ^0.20.3
  url_strategy: ^0.2.0

  #*Services
  url_launcher: ^6.0.12
  http: ^1.1.0

  #*Utilities
  collapsible_sidebar: ^2.0.1+2
  animated_text_kit: ^4.2.1
  simple_animations: ^5.0.2
  oktoast: ^3.1.3+1
  intl: ^0.19.0
  icons_plus: ^4.0.0
  flutter_neumorphic_plus: ^3.3.0

  animations: ^2.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.1.4
  change_app_package_name: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
